### ISSUE TITLE
A Problem With Bridj

### ISSUE THREAD

**Issue by ANightCoder** [nativelibs4java/nativelibs4java#393]
@ochafik  Hi
When i use webcam capture https://github.com/sarxos/webcam-capture from @sarxos i meet some exception with bridj ,following exception

java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\USER\AppData\Local\Temp\BridJExtractedLibraries7239214121169806436\OpenIMAJGrabber.dll'

at org.bridj.BridJ.getNativeLibrary(BridJ.java:952) 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:931) 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:543) 
at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:652) 
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:858) 
at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:785) 
at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:249) 
at org.bridj.BridJ.initialize(BridJ.java:1000) 
at org.bridj.NativeObject.(NativeObject.java:49) 
at org.bridj.StructObject.(StructObject.java:44) 
at org.bridj.cpp.CPPObject.(CPPObject.java:52) 
at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.(OpenIMAJGrabber.java:64) 
at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:56)
at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:61) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) 
com.github.sarxos.webcam.WebcamException: java.util.concurrent.ExecutionException: com.github.sarxos.webcam.WebcamException: Cannot execute task

Bridj Version : both of this version can not work
1.bridj-0.6.2-windows-only
2.bridj-0.6.3-20130316.174623-12-windows-only
3.bridj-0.6.3-20130316.190111-13

PC: Win7 32bit Ul Ultimate

Look forward to your reply ! thanks

**Comment by jealfonso** [comment]
I have the Microsoft libraries installed and changed the driver to 
 Webcam.setDriver(new LtiCivilDriver());
However it continues to say OpenIMAJGrabber.dll' was not loaded, despite is there in java where it looks for and also in windows

Please help
